config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :restaurants do # "resources :restaurants" is the code that creates our various restaurant related URL's...To add a new one we need to go to the next line...
    collection do
      get 'search'
    end

    resources :reviews, except: [:show, :index]
  end

  get 'pages/about'

  get 'pages/contact'

  root 'restaurants#index'

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	mount_uploader :image, ImageUploader

	# Type "searchkick" into the model file that we want to be able to search....
	searchkick

	has_many :reviews


	validates :name, :address, :phone, :website, :image, presence: true
	#validates :phone, format: { with: /\A\(d{3}\) \d{3}-\d{4}\z/, 
		#message: "must be in the format: (123) 456-7890." }
	validates :website, format: { with: /\Ahttps?:\/\/.*\z/, 
		message: "must start with http:// or https://" }
	#validates :address, format: { with: /\A\d+[^,]+,[^,]+, [A-Z]{2} \d{5}\z/, 
		#message: "must be in the format: 350 Fifth Avenue, New York, NY 10118" }








end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]


  before_action :authenticate_user!, except: [:search, :index, :show]

  before_action :check_user, except: [:search, :index, :show]
  #Everyone should be able to look at the index page, and the individual restaurants' Show pages...


  

#*******************    SEARCH FUNCTIONALITY  ****************************
  def search
    if params[:search].present? #IF SEARCH TERMS ENTERED....
      @restaurants = Restaurant.search(params[:search])   #SEARCH restaurants Database for matching terms...
    else  # These matches are stored in a variable called "@restaurants"
      @restaurants = Restaurant.all  #If search was left blank, just display all restaurants in our Database!!!
    end
  end
#*******************    SEARCH FUNCTIONALITY  ****************************
# Now we need to write our own Search page view to display the results....search.html.erb









  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
    #@restaurants = Restaurant.order(date: :desc).page(params[:page]).per(5)
    
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    #@restaurants = Restaurant.all
    #defining @reviews and showing review for the restaurant
    @reviews = Review.where(restaurant_id: @restaurant.id).order("created_at DESC")
    #take all our restaurant ratings, average them, round to 2 decimal places.
    # BUT, if there aren't any reviews, it won't have anything to average, and 
    # will give us an error. so we need to say if.....
    if @reviews.blank?
      @avg_rating = 0
    else
      @avg_rating = @reviews.average(:rating).round(2)
    end


  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end



    def check_user
      unless current_user.admin?
        redirect_to root_url, alert: "Sorry, only admins can do that!"
      end
    end







    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :phone, :website, :image)
    end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant, :html => { multipart: true }) do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissible">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h3><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h3>

      <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control", placeholder: "Restaurant Name" %>
  </div>
  <div class="form-group">
    <%= f.label :address %><br>
    <%= f.text_field :address, class: "form-control", placeholder: "123 Fake Street, Somewhere City, NA 12345" %>
  </div>
  <div class="form-group">
    <%= f.label :phone %><br>
    <%= f.text_field :phone, class: "form-control", placeholder: "(123) 456-7890" %>
  </div>
  <div class="form-group">
    <%= f.label :website %><br>
    <%= f.text_field :website, class: "form-control", placeholder: "http://www.restaurantwebsite.com" %>
  </div>
  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<div class="jumbotron tablecontainer">
<h2>Editing Restaurant</h2>

<%= render 'form' %>

<%= link_to 'Show', @restaurant, class: "btn btn-link" %> |
<%= link_to 'Back', restaurants_path, class: "btn btn-link" %>
</div>

app/views/restaurants/index.html.erb
<div class="jumbotron jumboBG">
  <div class="container">
  <div class="welcomeTitle">
  <h1>Welcome to the Pulaski <br> Restaurant Review!</h1>
  </div>
  <h2><em>A great way to find local restaurants in the Pulaski County and New River Valley, Virginia area.</em></h2>
  <h3><em>Explore the favorite restaurants, diners, pastry shops, and eateries in your community.<br> 
  Leave reviews and ratings for your fellow restaraunt lovers!</em></h3>
  </div>


</div>
<div class="jumbotron tablecontainer">
<div class="table-responsive">
<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Address</th>
      
      <th>Website</th>
      <!--th colspan="3"></th-->
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td class="tdName"><%= link_to restaurant.name, restaurant, class: "btn btn-link restaurantname" %></td>
        <td class="tdPhone"><%= restaurant.phone %></td>
        <td class="tdAddress"><%= restaurant.address %></td>
       
        <td class="tdWebsite"><%= link_to restaurant.website, restaurant.website %></td>

      </tr>
    <% end %>
  </tbody>
</table>

</div><!--END .table-responsive-->

</div><!--End .tablecontainer-->

<br>



<% if user_signed_in? && current_user.admin? %>

  <div class="jumbotron admincontrols"><br>
  <h2>Admin Add-Restaurant Controls:</h2>
  <%= link_to 'New Restaurant', new_restaurant_path, class: "btn btn-primary" %>
  </div>

<% end %>

app/views/restaurants/new.html.erb
<div class="jumbotron tablecontainer">

<h2>New Restaurant</h2>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path, class: "btn btn-link" %>
</div>

app/views/restaurants/search.html.erb
<div class="jumbotron tablecontainer">
<h2>Search Results</h2>
<br>
<div class="table-responsive">
<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Address</th>
      
      <th>Website</th>
      <!--th colspan="3"></th-->
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td class="tdName"><%= link_to restaurant.name, restaurant, class: "btn btn-link restaurantname" %></td>
        <td class="tdPhone"><%= restaurant.phone %></td>
        <td class="tdAddress"><%= restaurant.address %></td>
       
        <td class="tdWebsite"><%= link_to restaurant.website, restaurant.website %></td>

      </tr>
    <% end %>
  </tbody>
</table>

</div><!--END .table-responsive-->

</div><!--End .tablecontainer-->

app/views/restaurants/show.html.erb
<div class="jumbotron restaurantcontainer">

<div class="row">
<div class="col-md-4">

<div class="restaurantinfo">
<h2>
	<%= @restaurant.name %>
</h2>
<!-- Showing AVERAGE star rating for this restaurant!-->
<div class="star-rating" data-score= <%= @avg_rating %> ></div>
<!-- This time instead of review.rating, we'll use the @avg_rating variable we JUST defined in the RestaurantsController show action!-->


<!--The AVG star rating means little without knowing the total # of reviews, so...-->
<p>Average rating, <%= "#{@reviews.length} total reviews" %></p>


<!--#{} is a special feature of rails called string interpolation.  Ruby code inside curly braces will be calculated and then placed on the page as text.-->


<%= image_tag @restaurant.image_url %>





<p>
  <h4><strong>Address:</strong></h4>
  <%= @restaurant.address %>
</p>

<p>
  <h4><strong>Phone:</strong></h4>
  <%= @restaurant.phone %>
</p>

<p>
  <h4><strong>Website:</strong></h4>
  <%= link_to @restaurant.website, @restaurant.website, class: "link" %>
</p>






<% if user_signed_in? && current_user.admin? %>
	<%= link_to edit_restaurant_path(@restaurant), class: "btn btn-primary" do %>
		<span class="glyphicon glyphicon-edit"></span> <span> </span> Edit Restaurant
	<% end %>	
<% end %>







<br/>
<%= link_to new_restaurant_review_path(@restaurant), class: "btn btn-primary writeareviewbutton" do %>
	<span class="glyphicon glyphicon-pencil"></span> Write a Review
<% end %>

 
<br/>
<% if user_signed_in? && current_user.admin? %>
	<%= link_to @restaurant, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger deletebutton" do %>
		<span class="glyphicon glyphicon-remove-sign"></span>  Delete Restaurant
	<% end %>
<% end %> 

<br>

<%= link_to  restaurants_path, class: "btn btn-primary backbutton" do %>
	<span class="glyphicon glyphicon-circle-arrow-left"></span>  Back to Index
<% end %>


</div><!--END .restaurantinfo-->












<br/>
<!--a class="btn btn-primary backbutton2" href="/restaurants"><span class="glyphicon glyphicon-arrow-left"></span><span class="glyphicon glyphicon-arrow-left"></span> Back</a-->



</div><!--END col-md-4 -->
<div class="col-md-8">


<!--	WANT TO ADD GLYPHICONS TO BUTTONS  -->



<!--    REVIEWS SECTION    -->
<div class="mapscontainer">
<h2>Map</h2>
	<iframe class="googleMap"

	  width="100%"
	  height="300"

	  frameborder="0" style="border:0"
	  src="https://www.google.com/maps/embed/v1/place?key=AIzaSyCOuPTTq4UuEXnKY_AZVaM-HCfjbzUIRtI
	    &q=<%= @restaurant.address.parameterize %>&zoom=14" allowfullscreen>
	</iframe>
<!--My Google Maps Embed API key:  AIzaSyCOuPTTq4UuEXnKY_AZVaM-HCfjbzUIRtI-->

</div>


<br>








<div class="reviewscontainer">
<h2>Reviews</h2>

<!--		NOT SURE IF I'LL KEEP THE TABLE.. NOT WORKING WELL.  -->

<% if @reviews.blank? %>
	<h3>No reviews yet.  Be the first to write one!</h3>
<% else %>  

<!--**************************************************************************8-->
<!--    ***  Now we want to place our Reviews in a Table format! ***    -->
<div class="container panel-body table-responsive">
<table class="table table-condensed">

<!--	*********** SEPARATE TABLE INTO 2 COLUMNS ALSO! *********-->
<!--<thead>
	<tr>
		<th class="col-md-3"></th>
		<th class="col-md-9"></th>-->
		<!--****************************IMPORTANT!!!!!********************-->
		<!--Keep in mind that these grids are SMALLER than the others because they are nested inside the table, NOT the full width of our page!  Bootstrap allows you to create grid layouts WITHIN grid layouts!-->
	<!--</tr>
</thead>-->


<tbody>
	<% @reviews.each do |review| %>
		<tr>
			<td>
				<h4>
					<%= "#{review.user.first_name.capitalize} #{review.user.last_name.capitalize[0]}." %>
				</h4>
				<p><%= review.created_at.strftime("%-m/%-d/%-y") %></p>



				<div class="star-rating" data-score= <%= review.rating %> ></div>
				<p class="reviewtext"><%= h(review.comment).gsub(/\n/, '<br/>').html_safe %>
					
				
<!--			Check to see if review author signed in, or admin........-->

<!--	If so, give them links to edit or destroy the review.........-->
			
				<% if user_signed_in? %>
					<% if (review.user == current_user) || (current_user.admin?) %><br>
						<%= link_to "Edit your review", edit_restaurant_review_path(@restaurant, review) %> | 
						<%= link_to "Delete", restaurant_review_path(@restaurant, review), method: :delete %>
					<% end %>
				<% end %>
					</p>


			</td>
		</tr>

	<% end %>
	</tbody>
	</table>
<!--**************************************************************************8-->



<% end %>

</div>
</div>


</div><!--END col-md-8 -->
</div><!--END .row-->


</div>


<script> //DISPLAY OUR STAR RATING SYSTEM ON OUR .star-rating DIV ABOVE!!!
	
//declare our Amazon s3 star images path
	$('.star-rating').raty({path: 'https://s3.amazonaws.com/pulaski-restaurant-review/stars', 
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
	}});



	//$('.star-rating').raty();
</script>