config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :restaurants do # "resources :restaurants" is the code that creates our various restaurant related URL's...To add a new one we need to go to the next line...
    collection do
      get 'search'
    end

    resources :reviews, except: [:show, :index]
  end

  get 'pages/about'

  get 'pages/contact'

  root 'restaurants#index'

end

app/views/layouts/_bootstrap.html.erb
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

app/views/layouts/_footer.html.erb
<div class="footer navbar-light">


<p>Copyright &copy 2016 by Chris Moncure            

</div>



<!--			JAVASCRIPTS   			-->
	<!--ADDING JQUERY FOR ALERTS-->
<!-- Latest compiled and minified jQuery -->
	<script src="//code.jquery.com/jquery-3.1.1.min.js"></script>


	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-fixed">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!--<a class="navbar-brand" href="/">Pulaski</a>
      <br>
      <a class="navbar-brand" href="/">Restaurant Review</a>-->
     
    

      <!--Original nav-brand link-->

      <!--%= #link_to "Pulaski Restaurant Review", root_path, class: "navbar-brand" %-->
     

      <!--HTML version of nav-brand link to make it work the way I wanted...-->

      <!--a class="navbar-brand"  href="#home">
        <span><p>Pulaski Restaurant</p><p>Review</p></span>
        
      </a-->
    

      <!--Attempt to blend the two...-->
      <%= link_to root_path do %>
        <span class="navbar-brand"><p>Pulaski Restaurant</p><p>Review</p></span>
   
      <% end %>


    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/pages/about">About <span class="sr-only">(current)</span></a></li>
        
        <!--<li><a href="/pages/contact">Contact</a></li>-->
        <li><%= link_to "Contact", pages_contact_path %></li>	

      </ul>




      <!--  **** SEARCH FORM **** -->


      <!--  REPLACE HTML SEARCH FORM WITH EMBEDDED RUBY SEARCH FORM OF OUR OWN....-->
      <%= form_tag search_restaurants_path, method: :get, class: "navbar-form navbar-left" do %>
        <p>
          <%= text_field_tag :search, params[:search], class: "form-control" %>
          <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
        </p>
      <% end %>


      <!--form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form-->
      <!--  **** SEARCH FORM **** -->









			<ul class="nav navbar-nav navbar-right">
	      <% if user_signed_in? %>

	      	<li><%= link_to "Edit Profile", edit_user_registration_path %></li>
	      	<li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
	      <% else %>
	        <li><%= link_to "Sign up", new_user_registration_path %></li>
	        <li><%= link_to "Sign in", new_user_session_path %></li>
       <% end %>


      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pulaski Restaurant Review</title>

  <%= render 'layouts/bootstrap' %>

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

</head>
<body class="backgroundBG">

<%= render 'layouts/navbar' %>
<br>	
		<div class="container-fluid">

		<!--p class="notice"><%#= notice %></p>
		<p class="alert"><%#= alert %></p-->



<!--REPLACING DEFAULT ALERTS WITH BOOTSTRAP STYLED ONES-->
<!--WORKS WITH RAILS 4.2 OR LATER.  IF USING 4.1 OR EARLIER, 
NEED TO DELETE QUOTES AROUND "notice" and add a : before (ex.  :notice)-->

<!--This basically adds Bootstrap styling to our Devise error messages!-->

    <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissable">
          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
      <% end %>
    <% end %> 

<!--******************************************************-->




		<br>
			<%= yield %>
			<div class="pushdown"></div>
		</div><!--END container-fluid DIV-->
   

  
	<%= render 'layouts/footer' %>
</body>
</html>